// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_GZpsIMitc4YOYR88Z7PVajtcQSqDO2E',
    appId: '1:766257278398:web:ff92ce442abdb14f111def',
    messagingSenderId: '766257278398',
    projectId: 'timacheck',
    authDomain: 'timacheck.firebaseapp.com',
    storageBucket: 'timacheck.firebasestorage.app',
    measurementId: 'G-FFPPEH0H6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFAgPbOA3FBfP4aSIA44SAd4sNS3pQEgA',
    appId: '1:766257278398:android:b88ad9924df860de111def',
    messagingSenderId: '766257278398',
    projectId: 'timacheck',
    storageBucket: 'timacheck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFy0SqRpmDFhbYmqIn9xJy8lCu0kVops',
    appId: '1:766257278398:ios:1b961c53efd1a27a111def',
    messagingSenderId: '766257278398',
    projectId: 'timacheck',
    storageBucket: 'timacheck.firebasestorage.app',
    iosBundleId: 'com.abomis.abdc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMFy0SqRpmDFhbYmqIn9xJy8lCu0kVops',
    appId: '1:766257278398:ios:1b961c53efd1a27a111def',
    messagingSenderId: '766257278398',
    projectId: 'timacheck',
    storageBucket: 'timacheck.firebasestorage.app',
    iosBundleId: 'com.abomis.abdc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_GZpsIMitc4YOYR88Z7PVajtcQSqDO2E',
    appId: '1:766257278398:web:67f580e87b502fad111def',
    messagingSenderId: '766257278398',
    projectId: 'timacheck',
    authDomain: 'timacheck.firebaseapp.com',
    storageBucket: 'timacheck.firebasestorage.app',
    measurementId: 'G-KJ8FW1ZXYH',
  );

}