import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
String? iso3ToIso2(String iso3) {
  const map3to2 = {
    'AFG': 'af',
    'ALA': 'ax',
    'ALB': 'al',
    'DZA': 'dz',
    'ASM': 'as',
    'AND': 'ad',
    'AGO': 'ao',
    'AIA': 'ai',
    'ATA': 'aq',
    'ATG': 'ag',
    'ARG': 'ar',
    'ARM': 'am',
    'ABW': 'aw',
    'AUS': 'au',
    'AUT': 'at',
    'AZE': 'az',
    'BHS': 'bs',
    'BHR': 'bh',
    'BGD': 'bd',
    'BRB': 'bb',
    'BLR': 'by',
    'BEL': 'be',
    'BLZ': 'bz',
    'BEN': 'bj',
    'BMU': 'bm',
    'BTN': 'bt',
    'BOL': 'bo',
    'BES': 'bq',
    'BIH': 'ba',
    'BWA': 'bw',
    'BVT': 'bv',
    'BRA': 'br',
    'IOT': 'io',
    'BRN': 'bn',
    'BGR': 'bg',
    'BFA': 'bf',
    'BDI': 'bi',
    'CPV': 'cv',
    'KHM': 'kh',
    'CMR': 'cm',
    'CAN': 'ca',
    'CYM': 'ky',
    'CAF': 'cf',
    'TCD': 'td',
    'CHL': 'cl',
    'CHN': 'cn',
    'CXR': 'cx',
    'CCK': 'cc',
    'COL': 'co',
    'COM': 'km',
    'COG': 'cg',
    'COD': 'cd',
    'COK': 'ck',
    'CRI': 'cr',
    'CIV': 'ci',
    'HRV': 'hr',
    'CUB': 'cu',
    'CUW': 'cw',
    'CYP': 'cy',
    'CZE': 'cz',
    'DNK': 'dk',
    'DJI': 'dj',
    'DMA': 'dm',
    'DOM': 'do',
    'ECU': 'ec',
    'EGY': 'eg',
    'SLV': 'sv',
    'GNQ': 'gq',
    'ERI': 'er',
    'EST': 'ee',
    'SWZ': 'sz',
    'ETH': 'et',
    'FLK': 'fk',
    'FRO': 'fo',
    'FJI': 'fj',
    'FIN': 'fi',
    'FRA': 'fr',
    'GUF': 'gf',
    'PYF': 'pf',
    'ATF': 'tf',
    'GAB': 'ga',
    'GMB': 'gm',
    'GEO': 'ge',
    'DEU': 'de',
    'GHA': 'gh',
    'GIB': 'gi',
    'GRC': 'gr',
    'GRL': 'gl',
    'GRD': 'gd',
    'GLP': 'gp',
    'GUM': 'gu',
    'GTM': 'gt',
    'GGY': 'gg',
    'GIN': 'gn',
    'GNB': 'gw',
    'GUY': 'gy',
    'HTI': 'ht',
    'HMD': 'hm',
    'VAT': 'va',
    'HND': 'hn',
    'HKG': 'hk',
    'HUN': 'hu',
    'ISL': 'is',
    'IND': 'in',
    'IDN': 'id',
    'IRN': 'ir',
    'IRQ': 'iq',
    'IRL': 'ie',
    'IMN': 'im',
    'ISR': 'il',
    'ITA': 'it',
    'JAM': 'jm',
    'JPN': 'jp',
    'JEY': 'je',
    'JOR': 'jo',
    'KAZ': 'kz',
    'KEN': 'ke',
    'KIR': 'ki',
    'PRK': 'kp',
    'KOR': 'kr',
    'KWT': 'kw',
    'KGZ': 'kg',
    'LAO': 'la',
    'LVA': 'lv',
    'LBN': 'lb',
    'LSO': 'ls',
    'LBR': 'lr',
    'LBY': 'ly',
    'LIE': 'li',
    'LTU': 'lt',
    'LUX': 'lu',
    'MAC': 'mo',
    'MDG': 'mg',
    'MWI': 'mw',
    'MYS': 'my',
    'MDV': 'mv',
    'MLI': 'ml',
    'MLT': 'mt',
    'MHL': 'mh',
    'MTQ': 'mq',
    'MRT': 'mr',
    'MUS': 'mu',
    'MYT': 'yt',
    'MEX': 'mx',
    'FSM': 'fm',
    'MDA': 'md',
    'MCO': 'mc',
    'MNG': 'mn',
    'MNE': 'me',
    'MSR': 'ms',
    'MAR': 'ma',
    'MOZ': 'mz',
    'MMR': 'mm',
    'NAM': 'na',
    'NRU': 'nr',
    'NPL': 'np',
    'NLD': 'nl',
    'NCL': 'nc',
    'NZL': 'nz',
    'NIC': 'ni',
    'NER': 'ne',
    'NGA': 'ng',
    'NIU': 'nu',
    'NFK': 'nf',
    'MNP': 'mp',
    'NOR': 'no',
    'OMN': 'om',
    'PAK': 'pk',
    'PLW': 'pw',
    'PSE': 'ps',
    'PAN': 'pa',
    'PNG': 'pg',
    'PRY': 'py',
    'PER': 'pe',
    'PHL': 'ph',
    'PCN': 'pn',
    'POL': 'pl',
    'PRT': 'pt',
    'PRI': 'pr',
    'QAT': 'qa',
    'REU': 're',
    'ROU': 'ro',
    'RUS': 'ru',
    'RWA': 'rw',
    'BLM': 'bl',
    'SHN': 'sh',
    'KNA': 'kn',
    'LCA': 'lc',
    'MAF': 'mf',
    'SPM': 'pm',
    'VCT': 'vc',
    'WSM': 'ws',
    'SMR': 'sm',
    'STP': 'st',
    'SAU': 'sa',
    'SEN': 'sn',
    'SRB': 'rs',
    'SYC': 'sc',
    'SLE': 'sl',
    'SGP': 'sg',
    'SXM': 'sx',
    'SVK': 'sk',
    'SVN': 'si',
    'SLB': 'sb',
    'SOM': 'so',
    'ZAF': 'za',
    'SGS': 'gs',
    'SSD': 'ss',
    'ESP': 'es',
    'LKA': 'lk',
    'SDN': 'sd',
    'SUR': 'sr',
    'SJM': 'sj',
    'SWE': 'se',
    'CHE': 'ch',
    'SYR': 'sy',
    'TWN': 'tw',
    'TJK': 'tj',
    'TZA': 'tz',
    'THA': 'th',
    'TLS': 'tl',
    'TGO': 'tg',
    'TKL': 'tk',
    'TON': 'to',
    'TTO': 'tt',
    'TUN': 'tn',
    'TUR': 'tr',
    'TKM': 'tm',
    'TCA': 'tc',
    'TUV': 'tv',
    'UGA': 'ug',
    'UKR': 'ua',
    'ARE': 'ae',
    'GBR': 'gb',
    'USA': 'us',
    'UMI': 'um',
    'URY': 'uy',
    'UZB': 'uz',
    'VUT': 'vu',
    'VEN': 've',
    'VNM': 'vn',
    'VGB': 'vg',
    'VIR': 'vi',
    'WLF': 'wf',
    'ESH': 'eh',
    'YEM': 'ye',
    'ZMB': 'zm',
    'ZWE': 'zw',
    'XKX': 'xk',
  };

  return map3to2[iso3.toUpperCase()];
}
/// A utility class to display country flags in SVG format.
class MyCountryFlagsPro {
  /// A list of valid country codes that have corresponding flag assets.
  static const List<String> validCountryCodes = [
    'af',
    'ag',
    'ai',
    'al',
    'am',
    'ao',
    'aq',
    'ar',
    'as',
    'at',
    'au',
    'aw',
    'ax',
    'az',
    'ba',
    'bb',
    'bd',
    'be',
    'bf',
    'bg',
    'bh',
    'bi',
    'bj',
    'bl',
    'bm',
    'bn',
    'bo',
    'bq',
    'br',
    'bs',
    'bt',
    'bv',
    'bw',
    'by',
    'bz',
    'ca',
    'cc',
    'cd',
    'cf',
    'cg',
    'ch',
    'ci',
    'ck',
    'cl',
    'cm',
    'cn',
    'co',
    'cr',
    'cu',
    'cv',
    'cw',
    'cx',
    'cy',
    'cz',
    'de',
    'dj',
    'dk',
    'dm',
    'do',
    'dz',
    'ec',
    'ee',
    'eg',
    'eh',
    'er',
    'es',
    'et',
    'eu',
    'fi',
    'fj',
    'fk',
    'fm',
    'fo',
    'fr',
    'ga',
    'gb',
    'gb-eng',
    'gb-nir',
    'gb-sct',
    'gb-wls',
    'gd',
    'ge',
    'gf',
    'gg',
    'gh',
    'gi',
    'gl',
    'gm',
    'gn',
    'gp',
    'gq',
    'gr',
    'gs',
    'gt',
    'gu',
    'gw',
    'gy',
    'hk',
    'hm',
    'hn',
    'hr',
    'ht',
    'hu',
    'id',
    'ie',
    'il',
    'im',
    'in',
    'io',
    'iq',
    'ir',
    'is',
    'it',
    'je',
    'jm',
    'jo',
    'jp',
    'ke',
    'kg',
    'kh',
    'ki',
    'km',
    'kn',
    'kp',
    'kr',
    'kw',
    'ky',
    'kz',
    'la',
    'lb',
    'lc',
    'li',
    'lk',
    'lr',
    'ls',
    'lt',
    'lu',
    'lv',
    'ly',
    'ma',
    'mc',
    'md',
    'me',
    'mf',
    'mg',
    'mh',
    'mk',
    'ml',
    'mm',
    'mn',
    'mo',
    'mp',
    'mq',
    'mr',
    'ms',
    'mt',
    'mu',
    'mv',
    'mw',
    'mx',
    'my',
    'mz',
    'na',
    'nc',
    'ne',
    'nf',
    'ng',
    'ni',
    'nl',
    'no',
    'np',
    'nr',
    'nu',
    'nz',
    'om',
    'pa',
    'pe',
    'pf',
    'pg',
    'ph',
    'pk',
    'pl',
    'pm',
    'pn',
    'pr',
    'ps',
    'pt',
    'pw',
    'py',
    'qa',
    're',
    'ro',
    'rs',
    'ru',
    'rw',
    'sa',
    'sb',
    'sc',
    'sd',
    'se',
    'sg',
    'sh',
    'si',
    'sj',
    'sk',
    'sl',
    'sm',
    'sn',
    'so',
    'sr',
    'ss',
    'st',
    'sv',
    'sx',
    'sy',
    'sz',
    'tc',
    'td',
    'tf',
    'tg',
    'th',
    'tj',
    'tk',
    'tl',
    'tm',
    'tn',
    'to',
    'tr',
    'tt',
    'tv',
    'tw',
    'tz',
    'ua',
    'ug',
    'um',
    'us',
    'uy',
    'uz',
    'va',
    'vc',
    've',
    'vg',
    'vi',
    'vn',
    'vu',
    'wf',
    'ws',
    'xk',
    'ye',
    'yt',
    'za',
    'zm',
    'zw',
    'ad',
    'ae',
  ];

  static const Map<String, String> countryCodeAndName = {
    'af': 'Afghanistan',
    'ag': 'Antigua and Barbuda',
    'ai': 'Anguilla',
    'al': 'Albania',
    'am': 'Armenia',
    'ao': 'Angola',
    'aq': 'Antarctica',
    'ar': 'Argentina',
    'as': 'American Samoa',
    'at': 'Austria',
    'au': 'Australia',
    'aw': 'Aruba',
    'ax': 'Åland Islands',
    'az': 'Azerbaijan',
    'ba': 'Bosnia and Herzegovina',
    'bb': 'Barbados',
    'bd': 'Bangladesh',
    'be': 'Belgium',
    'bf': 'Burkina Faso',
    'bg': 'Bulgaria',
    'bh': 'Bahrain',
    'bi': 'Burundi',
    'bj': 'Benin',
    'bl': 'Saint Barthélemy',
    'bm': 'Bermuda',
    'bn': 'Brunei',
    'bo': 'Bolivia',
    'bq': 'Caribbean Netherlands',
    'br': 'Brazil',
    'bs': 'Bahamas',
    'bt': 'Bhutan',
    'bv': 'Bouvet Island',
    'bw': 'Botswana',
    'by': 'Belarus',
    'bz': 'Belize',
    'ca': 'Canada',
    'cc': 'Cocos (Keeling) Islands',
    'cd': 'Democratic Republic of the Congo',
    'cf': 'Central African Republic',
    'cg': 'Republic of the Congo',
    'ch': 'Switzerland',
    'ci': 'Ivory Coast',
    'ck': 'Cook Islands',
    'cl': 'Chile',
    'cm': 'Cameroon',
    'cn': 'China',
    'co': 'Colombia',
    'cr': 'Costa Rica',
    'cu': 'Cuba',
    'cv': 'Cape Verde',
    'cw': 'Curaçao',
    'cx': 'Christmas Island',
    'cy': 'Cyprus',
    'cz': 'Czech Republic',
    'de': 'Germany',
    'dj': 'Djibouti',
    'dk': 'Denmark',
    'dm': 'Dominica',
    'do': 'Dominican Republic',
    'dz': 'Algeria',
    'ec': 'Ecuador',
    'ee': 'Estonia',
    'eg': 'Egypt',
    'eh': 'Western Sahara',
    'er': 'Eritrea',
    'es': 'Spain',
    'et': 'Ethiopia',
    'eu': 'European Union',
    'fi': 'Finland',
    'fj': 'Fiji',
    'fk': 'Falkland Islands',
    'fm': 'Micronesia',
    'fo': 'Faroe Islands',
    'fr': 'France',
    'ga': 'Gabon',
    'gb': 'United Kingdom',
    'gb-eng': 'England',
    'gb-nir': 'Northern Ireland',
    'gb-sct': 'Scotland',
    'gb-wls': 'Wales',
    'gd': 'Grenada',
    'ge': 'Georgia',
    'gf': 'French Guiana',
    'gg': 'Guernsey',
    'gh': 'Ghana',
    'gi': 'Gibraltar',
    'gl': 'Greenland',
    'gm': 'Gambia',
    'gn': 'Guinea',
    'gp': 'Guadeloupe',
    'gq': 'Equatorial Guinea',
    'gr': 'Greece',
    'gs': 'South Georgia and the South Sandwich Islands',
    'gt': 'Guatemala',
    'gu': 'Guam',
    'gw': 'Guinea-Bissau',
    'gy': 'Guyana',
    'hk': 'Hong Kong',
    'hm': 'Heard Island and McDonald Islands',
    'hn': 'Honduras',
    'hr': 'Croatia',
    'ht': 'Haiti',
    'hu': 'Hungary',
    'id': 'Indonesia',
    'ie': 'Ireland',
    'il': 'Israel',
    'im': 'Isle of Man',
    'in': 'India',
    'io': 'British Indian Ocean Territory',
    'iq': 'Iraq',
    'ir': 'Iran',
    'is': 'Iceland',
    'it': 'Italy',
    'je': 'Jersey',
    'jm': 'Jamaica',
    'jo': 'Jordan',
    'jp': 'Japan',
    'ke': 'Kenya',
    'kg': 'Kyrgyzstan',
    'kh': 'Cambodia',
    'ki': 'Kiribati',
    'km': 'Comoros',
    'kn': 'Saint Kitts and Nevis',
    'kp': 'North Korea',
    'kr': 'South Korea',
    'kw': 'Kuwait',
    'ky': 'Cayman Islands',
    'kz': 'Kazakhstan',
    'la': 'Laos',
    'lb': 'Lebanon',
    'lc': 'Saint Lucia',
    'li': 'Liechtenstein',
    'lk': 'Sri Lanka',
    'lr': 'Liberia',
    'ls': 'Lesotho',
    'lt': 'Lithuania',
    'lu': 'Luxembourg',
    'lv': 'Latvia',
    'ly': 'Libya',
    'ma': 'Morocco',
    'mc': 'Monaco',
    'md': 'Moldova',
    'me': 'Montenegro',
    'mf': 'Saint Martin',
    'mg': 'Madagascar',
    'mh': 'Marshall Islands',
    'mk': 'North Macedonia',
    'ml': 'Mali',
    'mm': 'Myanmar',
    'mn': 'Mongolia',
    'mo': 'Macau',
    'mp': 'Northern Mariana Islands',
    'mq': 'Martinique',
    'mr': 'Mauritania',
    'ms': 'Montserrat',
    'mt': 'Malta',
    'mu': 'Mauritius',
    'mv': 'Maldives',
    'mw': 'Malawi',
    'mx': 'Mexico',
    'my': 'Malaysia',
    'mz': 'Mozambique',
    'na': 'Namibia',
    'nc': 'New Caledonia',
    'ne': 'Niger',
    'nf': 'Norfolk Island',
    'ng': 'Nigeria',
    'ni': 'Nicaragua',
    'nl': 'Netherlands',
    'no': 'Norway',
    'np': 'Nepal',
    'nr': 'Nauru',
    'nu': 'Niue',
    'nz': 'New Zealand',
    'om': 'Oman',
    'pa': 'Panama',
    'pe': 'Peru',
    'pf': 'French Polynesia',
    'pg': 'Papua New Guinea',
    'ph': 'Philippines',
    'pk': 'Pakistan',
    'pl': 'Poland',
    'pm': 'Saint Pierre and Miquelon',
    'pn': 'Pitcairn Islands',
    'pr': 'Puerto Rico',
    'ps': 'Palestine',
    'pt': 'Portugal',
    'pw': 'Palau',
    'py': 'Paraguay',
    'qa': 'Qatar',
    're': 'Réunion',
    'ro': 'Romania',
    'rs': 'Serbia',
    'ru': 'Russia',
    'rw': 'Rwanda',
    'sa': 'Saudi Arabia',
    'sb': 'Solomon Islands',
    'sc': 'Seychelles',
    'sd': 'Sudan',
    'se': 'Sweden',
    'sg': 'Singapore',
    'sh': 'Saint Helena',
    'si': 'Slovenia',
    'sj': 'Svalbard and Jan Mayen',
    'sk': 'Slovakia',
    'sl': 'Sierra Leone',
    'sm': 'San Marino',
    'sn': 'Senegal',
    'so': 'Somalia',
    'sr': 'Suriname',
    'ss': 'South Sudan',
    'st': 'São Tomé and Príncipe',
    'sv': 'El Salvador',
    'sx': 'Sint Maarten',
    'sy': 'Syria',
    'sz': 'Eswatini',
    'tc': 'Turks and Caicos Islands',
    'td': 'Chad',
    'tf': 'French Southern Territories',
    'tg': 'Togo',
    'th': 'Thailand',
    'tj': 'Tajikistan',
    'tk': 'Tokelau',
    'tl': 'Timor-Leste',
    'tm': 'Turkmenistan',
    'tn': 'Tunisia',
    'to': 'Tonga',
    'tr': 'Turkey',
    'tt': 'Trinidad and Tobago',
    'tv': 'Tuvalu',
    'tw': 'Taiwan',
    'tz': 'Tanzania',
    'ua': 'Ukraine',
    'ug': 'Uganda',
    'um': 'United States Minor Outlying Islands',
    'us': 'United States',
    'uy': 'Uruguay',
    'uz': 'Uzbekistan',
    'va': 'Vatican City',
    'vc': 'Saint Vincent and the Grenadines',
    've': 'Venezuela',
    'vg': 'British Virgin Islands',
    'vi': 'U.S. Virgin Islands',
    'vn': 'Vietnam',
    'vu': 'Vanuatu',
    'wf': 'Wallis and Futuna',
    'ws': 'Samoa',
    'xk': 'Kosovo',
    'ye': 'Yemen',
    'yt': 'Mayotte',
    'za': 'South Africa',
    'zm': 'Zambia',
    'zw': 'Zimbabwe',
    'ad': 'Andorra',
    'ae': 'United Arab Emirates'
  };




  /// Returns an SVG flag widget based on the given [countryCode].
  ///
  /// - [countryCode]: The country code in lowercase (e.g., 'us' for the USA).
  /// - [width]: The width of the flag (default is 50.0).
  /// - [height]: The height of the flag (default is 50.0).
  ///
  /// If the country code is invalid, an error widget is displayed.
  static Widget getFlag(dynamic countryCode,
      {double width = 22.0,
        double height = 16.0,
        BoxFit fit = BoxFit.fill,
        BorderRadius? borderRadius,
        Color borderColor = Colors.transparent,
        double borderWidth = 2,
        Widget? loadingWidget,
        Widget? errorWidget
      }) {
    // Validate the country code
    countryCode = "${countryCode}";
    if(countryCode.length==3){
      countryCode = "$countryCode";
      countryCode = iso3ToIso2(countryCode)??countryCode;
    }
    if (!validCountryCodes.contains(countryCode.toLowerCase())) {
      return errorWidget ??
          Center(
            child: Icon(Icons.error)
          );
    }

    // Construct the asset path for the flag SVG
    String flagAsset = 'packages/country_flags_pro/assets/svg/$countryCode.svg';

    /// Helper widget to display an error message.
    return Container(
      key: Key(countryCode),
      width: width,
      height: height,
      decoration: BoxDecoration(
          borderRadius: borderRadius ?? BorderRadius.circular(20),
          border: Border.all(
            color: borderColor,
            width: borderWidth,
          )),
      child: ClipRRect(
        borderRadius: borderRadius ?? BorderRadius.circular(20),
        child: SvgPicture.asset(
          flagAsset,
          width: width,
          height: height,
          fit: fit,
          placeholderBuilder: (BuildContext context) =>
          loadingWidget ??
              SizedBox(
                width: width,
                height: height,
                child: Center(
                  child: CircularProgressIndicator(
                    color: borderColor,
                  ),
                ),
              ), // Loading
        ),
      ),
    );
  }
}
